export type PowProvider='railway'|'ngrok'; export type ModelType='default'|'expert'|'vision';
export const DEFAULT_TOKEN_VALUE='IVlSFv6JwO2TttyAhMW6Cu9/eMCDQhcfY0uHWu000SDnAyEwsYxtR8rFADgo22LM';
export const SECONDARY_TOKEN_VALUE='IObC1siEVWVU1u9jByDE6HjouP9yvj6l%2F1D%2Fz7VduSqhvDZL59KRy%2FUPbFHfGjvz';
export const RAILWAY_POW_BASE='https://web-production-c09dc.up.railway.app/pow';
export const NGROK_POW_BASE='https://immunize-quintet-trimmer.ngrok-free.dev/get_pow';
export function generateDeviceId(){ const chars='ABCDEFGHIJKLMNOPQRSTUVWXYZabcdefghijklmnopqrstuvwxyz0123456789+/'; return Array.from({length:88},()=>chars[Math.floor(Math.random()*chars.length)]).join(''); }
export function generateRangersId(){ const ts=BigInt(Date.now()); const rv=BigInt(Math.floor(1000000000+Math.random()*8999999999)); return ((ts<<32n)|rv).toString(); }
export function getTzOffset(){ return (new Date().getTimezoneOffset()*-60).toString(); }
export function buildFullHeaders(powResponse:string, token:string){ return {'User-Agent':'DeepSeek/2.1.1 Android/36','Accept':'application/json','Accept-Encoding':'gzip','Content-Type':'application/json','x-client-platform':'android','x-client-version':'2.1.1','x-client-locale':'ar','x-client-bundle-id':'com.deepseek.chat','x-rangers-id':generateRangersId(),'x-client-timezone-offset':getTzOffset(),'x-device-id':generateDeviceId(),'x-os-version':'30','x-app-version':'2.1.1','Authorization':`Bearer ${token}`,'X-DS-PoW-Response':powResponse,'accept-charset':'UTF-8'}; }
export async function getFreshPow(token:string, powProvider:PowProvider='railway'){ const base=powProvider==='ngrok'?NGROK_POW_BASE:RAILWAY_POW_BASE; const read=async(url:string)=>{ const r=await fetch(url); if(r.status!==200) throw new Error(`فشل الحصول على POW: ${r.status}`); const data=await r.json(); if(!data.pow_response&&!data.x_ds_pow_response) throw new Error(`استجابة POW غير مكتملة: ${JSON.stringify(data)}`); return {powResponse:data.x_ds_pow_response||data.pow_response,powData:data.solved_json};}; try{return await read(`${base}?authorization=${encodeURIComponent(token)}`)}catch{return read(base)} }
export async function createChatSession(token:string){ const r=await fetch('https://chat.deepseek.com/api/v0/chat_session/create',{method:'POST',headers:{'x-client-bundle-id':'com.deepseek.chat','x-client-platform':'web','x-client-version':'2.0.0','x-client-locale':'en_US','x-client-timezone-offset':getTzOffset(),'x-app-version':'2.0.0','Authorization':`Bearer ${token}`,'Content-Type':'application/json','Accept':'*/*'},body:JSON.stringify({})}); const data=await r.json(); const id=data?.data?.biz_data?.chat_session?.id; if(!id) throw new Error('استجابة غير صالحة من الخادم: '+JSON.stringify(data)); return id; }
export function parseDeepSeekLine(line:string,state:any,cbs:any){ if(!line.startsWith('data: ')) return; try{ const item=JSON.parse(line.slice(6)); if(!state.first&&item.request_message_id&&item.response_message_id){ state.requestMessageId=item.request_message_id; state.responseMessageId=item.response_message_id; state.first=true; cbs.onFirstResponse?.({requestMessageId:state.requestMessageId,responseMessageId:state.responseMessageId,sessionId:state.sessionId}); }
 const frags=item?.v?.response?.fragments; if(frags) for(const frag of frags){ if(frag.type==='SEARCH'&&frag.results?.length){ state.searchResults=frag.results.map((r:any)=>({url:r.url,title:r.title,snippet:r.snippet,site_name:r.site_name,site_icon:r.site_icon})); cbs.onSearchResults?.(state.searchResults);} if(frag.type==='THINKING'){state.thinkingText+=(frag.content||''); cbs.onThinkingChunk?.(state.thinkingText);} if(frag.type==='RESPONSE') state.text+=(frag.content||''); }
 if(typeof item?.v==='string') state.text+=item.v; if(item?.p==='response/fragments/-1/content'&&item.o==='APPEND'&&item.v) state.text+=item.v; }catch{} }
export async function askDeepseekStream({prompt,sessionId,parentMessageId,onChunk,onFirstResponse,onSearchResults,onDone,onError,refFileIds=[],searchEnabled=true,thinkingEnabled=false,modelType='default',onThinkingChunk,token,powProvider='railway'}:any){ try{ if(!token) throw new Error('لا يوجد توكن API صالح للاستخدام'); const activeSessionId=sessionId||await createChatSession(token); const {powResponse,powData}=await getFreshPow(token,powProvider); const headers=buildFullHeaders(powResponse,token); const payload={chat_session_id:activeSessionId,parent_message_id:parentMessageId,prompt,ref_file_ids:refFileIds,thinking_enabled:thinkingEnabled,search_enabled:searchEnabled,model_type:modelType,action:null,preempt:false,pow:powData,stream:true}; const xhr=new XMLHttpRequest(); xhr.open('POST','https://chat.deepseek.com/api/v0/chat/completion'); Object.entries(headers).forEach(([k,v])=>xhr.setRequestHeader(k,String(v))); let idx=0; const state={text:'',thinkingText:'',searchResults:[],first:false,sessionId:activeSessionId}; xhr.onprogress=()=>{ const part=xhr.responseText.slice(idx); idx=xhr.responseText.length; part.split('\n').map(l=>l.trim()).forEach(l=>parseDeepSeekLine(l,state,{onFirstResponse,onSearchResults,onThinkingChunk})); onChunk?.(state.text);}; xhr.onload=()=> xhr.status>=200&&xhr.status<300?onDone?.({...state,sessionId:activeSessionId}):onError?.(new Error(`خطأ ${xhr.status}: ${xhr.responseText}`)); xhr.onerror=()=>onError?.(new Error('فشل الاتصال بالخادم')); xhr.send(JSON.stringify(payload)); }catch(e){ onError?.(e); } }
export async function callDeepSeek({token,model='default',systemPrompt,userMessage,storyContext='',searchEnabled=false,thinkingEnabled=false,powProvider='railway',onChunk,onDone,onError}:any){ const fullPrompt=`${systemPrompt}\n\n${storyContext}\n\n${userMessage}`; return askDeepseekStream({prompt:fullPrompt,token,modelType:model,searchEnabled,thinkingEnabled,powProvider,onChunk,onDone,onError}); }
